apiVersion: ncc.navercorp.com/v1
kind: HPA
metadata:
    name: hpa-{{ .Values.n2c.instance }}-{{ .Values.n2c.installation }}
spec:
    minReplicas: {{ .Values.replicas.min }}
    maxReplicas: {{ .Values.replicas.max }}
    # 어떤 대상을 오토스케일링 할 것인지 정의
    scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: {{ .Values.n2c.instance }}-{{ .Values.n2c.installation }}
    metrics:
        - type: Containers
          containers:
            containerName: app
            metric:
                name: cpu_usage
            target:
                type: AverageValue
                averageValue: {{ .Values.hpa.averageCpu }}
        - type: Containers
          containers:
              containerName: app
              metric:
                name: memory_usage_bytes
              target:
                type: AverageValue
                averageValue:  {{ .Values.hpa.averageMemory }}        