replicas:
  min: 1
  max: 10

n2c:
  application: api-gw
  instance: api-gw
  installation: installation
  version: version

app:
  image:
    name: dlgustn555/api-gw
    tag: 0.0.1
  resources:
    request:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 100m
      memory: 512Mi

nginx:
  image:
    name: nginx
    tag: latest
  configPath: /home1/irteam/apps/nginx/conf/custom
  resources:
    request:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 100m
      memory: 512Mi

PORT: 4000
DB_IP: 10.174.79.140
DB_PORT: 27017
hpa:
  averageCpu: 80m
  averageMemory: 409Mi
